'use strict';

/* =========================================================================
 * Gyakorló – kerdesek.js
 *
 * Itt van a gyakorló MINDEN tartalma. Új kérdéshez csak ezt a fájlt kell
 * szerkeszteni.
 *
 * TEMAK:            { id, targy, nev }
 *
 * KERDESEK (kvíz és vizsga):
 *   feleletválasztós: { t: 'téma id', q: 'kérdés', a: ['JÓ válasz', 'rossz', 'rossz', 'rossz'], m: 'magyarázat' }
 *                     – mindig az ELSŐ válasz a helyes, megjelenítéskor keveredik
 *   beírós:           { t, q, be: ['elfogadott', 'másik elfogadott'], m }
 *                     – kis/nagybetű és a szóközök nem számítanak
 *                     – ios: true esetén a válasz IOS parancs, rövidítve is elfogadja
 *
 * PARANCSFELADATOK (terminál):
 *   { t, q: 'feladat', lepesek: [{ p: 'prompt', c: 'parancs' }] }
 *   – c lehet tömb is, ha több jó megoldás van
 *   – a kulcsszavak rövidíthetők, ahogy az IOS-ben (conf t, int g0/0)
 *   – a {kapcsos} zárójelbe tett szó (név, jelszó) betűre pontosan kell
 *
 * KARTYAK (tanulókártyák): { t: 'pakli id', e: 'eleje', h: 'hátulja' }
 *   A parancsos kártyák a parancstár data.js-éből készülnek maguktól.
 * ========================================================================= */

const TEMAK = [
  { id: 'ospf-egy',        targy: 'Hálózatok II.',     nev: 'Egyterületű OSPF' },
  { id: 'ospf-tobb',       targy: 'Hálózatok II.',     nev: 'Többterületű OSPF' },
  { id: 'halo-alap',       targy: 'Hálózatok II.',     nev: 'Portok, címek, alapok' },
  { id: 'linux-tortenet',  targy: 'Szerverek – Linux', nev: 'Linux: történet' },
  { id: 'linux-jellemzok', targy: 'Szerverek – Linux', nev: 'Linux: jellemzők' },
  { id: 'linux-felepites', targy: 'Szerverek – Linux', nev: 'Linux: felépítés' }
];

const KERDESEK = [

  /* =====================================================================
   * EGYTERÜLETŰ OSPF
   * ===================================================================== */
  { t: 'ospf-egy', q: 'Milyen típusú forgalomirányító protokoll az OSPF?',
    a: ['Kapcsolatállapot-alapú (link-state)', 'Távolságvektor-alapú', 'Útvonalvektor-alapú', 'Hibrid'],
    m: 'Az OSPF link-state protokoll: minden router a terület teljes topológiáját ismeri.' },
  { t: 'ospf-egy', q: 'Mennyi az OSPF adminisztratív távolsága?', be: ['110'],
    m: 'OSPF = 110. Összehasonlításul: statikus 1, EIGRP 90, RIP 120.' },
  { t: 'ospf-egy', q: 'Melyik algoritmussal számolja ki az OSPF a legjobb utat?',
    a: ['Dijkstra SPF', 'Bellman–Ford', 'DUAL', 'Spanning Tree'],
    m: 'A Dijkstra-féle Shortest Path First algoritmus. A Bellman–Ford a RIP-é, a DUAL az EIGRP-é.' },
  { t: 'ospf-egy', q: 'Mi az OSPF metrikája?',
    a: ['Költség (cost), a sávszélességből számolva', 'Ugrásszám (hop count)', 'Sávszélesség és késleltetés együtt', 'Megbízhatóság és terhelés'],
    m: 'Költség = referencia-sávszélesség / interfész sávszélessége.' },
  { t: 'ospf-egy', q: 'Mennyi az alapértelmezett Hello időköz Ethernet hálózaton (másodpercben)?', be: ['10'],
    m: 'Hello 10 mp, Dead 40 mp – a Dead a Hello négyszerese.' },
  { t: 'ospf-egy', q: 'Mennyi az alapértelmezett Dead időköz Ethernet hálózaton (másodpercben)?', be: ['40'],
    m: 'A Dead időköz alapból a Hello négyszerese: 4 × 10 = 40 mp.' },
  { t: 'ospf-egy', q: 'Melyik multicast címre küldi egy OSPF router a Hello csomagokat?', be: ['224.0.0.5'],
    m: '224.0.0.5 = minden OSPF router. A 224.0.0.6 a DR-nek és a BDR-nek szól.' },
  { t: 'ospf-egy', q: 'Melyik multicast címen érhető el a DR és a BDR?', be: ['224.0.0.6'],
    m: 'A DROTHER routerek a 224.0.0.6 címre küldik a frissítéseket, a DR ezután a 224.0.0.5-re teríti.' },
  { t: 'ospf-egy', q: 'Mi dönt először a DR választásnál?',
    a: ['A legnagyobb interfész-prioritás', 'A legnagyobb router ID', 'A legkisebb költség', 'A legrégebben futó router'],
    m: 'Előbb a prioritás (alap 1), és csak egyenlőségnél a router ID.' },
  { t: 'ospf-egy', q: 'Mi történik, ha egy interfész OSPF prioritása 0?',
    a: ['A router azon a hálózaton soha nem lesz DR vagy BDR', 'A router biztosan DR lesz', 'Az OSPF leáll az interfészen', 'A router nem küld Hello csomagot'],
    m: 'A 0 prioritás kizárja a routert a választásból, de szomszédságot ettől még épít.' },
  { t: 'ospf-egy', q: 'Honnan lesz a router ID, ha nincs router-id parancs és van loopback interfész?',
    a: ['A legnagyobb loopback IP-cím', 'A legkisebb loopback IP-cím', 'A legnagyobb fizikai interfész IP-címe', 'A folyamatazonosítóból'],
    m: 'Sorrend: router-id parancs → legnagyobb loopback cím → legnagyobb aktív fizikai interfész címe.' },
  { t: 'ospf-egy', q: 'Melyik állapot jelzi, hogy két OSPF szomszéd adatbázisa teljesen megegyezik?',
    a: ['Full', 'Two-Way', 'Exchange', 'Loading'],
    m: 'Sorrend: Down → Init → Two-Way → ExStart → Exchange → Loading → Full.' },
  { t: 'ospf-egy', q: 'Melyik állapotban zajlik a DR/BDR választás?',
    a: ['Two-Way', 'Init', 'ExStart', 'Full'],
    m: 'A Two-Way állapotban már kétirányú a kapcsolat; többszörös hozzáférésű hálózaton itt választanak.' },
  { t: 'ospf-egy', q: 'Melyik OSPF csomag tartalmazza az adatbázis „tartalomjegyzékét”?',
    a: ['DBD (Database Description)', 'Hello', 'LSR', 'LSAck'],
    m: 'A DBD-ket összehasonlítva derül ki, mi hiányzik; azt LSR-rel kérik el, és LSU-ban érkezik.' },
  { t: 'ospf-egy', q: 'Melyik csomagban utaznak az LSA-k?',
    a: ['LSU (Link-State Update)', 'LSR (Link-State Request)', 'DBD', 'Hello'],
    m: 'Az LSU viszi az LSA-kat; az LSAck nyugtázza.' },
  { t: 'ospf-egy', q: 'Mennyi egy Gigabit Ethernet interfész OSPF költsége alapértelmezett referencia-sávszélességgel?', be: ['1'],
    m: 'Referencia 100 Mbps / 1000 Mbps = 0,1 → felfelé kerekítve 1. Ezért kell az auto-cost reference-bandwidth.' },
  { t: 'ospf-egy', q: 'Mennyi az alapértelmezett referencia-sávszélesség Mbps-ban?', be: ['100'],
    m: '100 Mbps. Emiatt a Fast Ethernet, a Gigabit és a 10 Gigabit is 1-es költségű.' },
  { t: 'ospf-egy', q: 'Mit csinál a passive-interface parancs OSPF-ben?',
    a: ['Nem küld Hello csomagot az interfészen, de a hálózatát hirdeti', 'Kiveszi a hálózatot a hirdetésből', 'Lekapcsolja az interfészt', 'A routert BDR-ré teszi'],
    m: 'A LAN felé felesleges és kockázatos Hello-t küldeni; a hálózat ettől még bekerül a hirdetésekbe.' },
  { t: 'ospf-egy', q: 'Melyik parancs mutatja az OSPF szomszédokat és az állapotukat?',
    be: ['show ip ospf neighbor'], ios: true,
    m: 'show ip ospf neighbor – itt látszik a FULL/DR, FULL/BDR, 2WAY/DROTHER állapot.' },
  { t: 'ospf-egy', q: 'Mi a wildcard maszk a 255.255.255.252 (/30) alhálózati maszkhoz?', be: ['0.0.0.3'],
    m: '255.255.255.255 − 255.255.255.252 = 0.0.0.3.' },
  { t: 'ospf-egy', q: 'Mi a wildcard maszk a /26-os hálózathoz?', be: ['0.0.0.63'],
    m: '/26 = 255.255.255.192; 255 − 192 = 63.' },
  { t: 'ospf-egy', q: 'Mennyi az OSPF IP-protokollszáma?', be: ['89'],
    m: 'Az OSPF közvetlenül IP fölött megy, protokollszáma 89 (nem TCP, nem UDP).' },
  { t: 'ospf-egy', q: 'Két router nem lesz OSPF szomszéd. Melyik NEM lehet az oka?',
    a: ['Eltér a folyamatazonosító (process ID)', 'Eltér a Hello időzítő', 'Eltér a terület száma', 'Más alhálózatban van a két interfész'],
    m: 'A folyamatazonosító csak helyi jelentőségű, nem kell egyeznie.' },
  { t: 'ospf-egy', q: 'Mi kell ahhoz, hogy a default-information originate tényleg hirdessen alapértelmezett utat?',
    a: ['Legyen alapértelmezett útvonal a router irányítótáblájában', 'A router legyen DR', 'Legyen loopback interfész', 'Semmi, magától hirdeti'],
    m: 'Előbb kell egy ip route 0.0.0.0 0.0.0.0 …, és azt terjeszti tovább az OSPF.' },

  /* =====================================================================
   * TÖBBTERÜLETŰ OSPF
   * ===================================================================== */
  { t: 'ospf-tobb', q: 'Melyik NEM a túl nagyra nőtt egyterületű OSPF problémája?',
    a: ['Túl sok DR választás', 'Nagy irányítótábla', 'Nagy kapcsolatállapot-adatbázis (LSDB)', 'Gyakori SPF-újraszámítás'],
    m: 'A három gond: nagy irányítótábla, nagy LSDB, gyakori SPF-számítás.' },
  { t: 'ospf-tobb', q: 'Hányas számú a gerinchálózati terület?', be: ['0', 'area 0'],
    m: 'Az area 0 a gerinc (tranzit) terület; minden más terület ehhez kapcsolódik.' },
  { t: 'ospf-tobb', q: 'Hogyan nevezzük azt a routert, amelynek interfészei különböző területekhez tartoznak?',
    a: ['ABR', 'ASBR', 'Belső router', 'DR'],
    m: 'ABR = Area Border Router, területi határrouter.' },
  { t: 'ospf-tobb', q: 'Melyik router csatlakozik külső (nem OSPF) hálózathoz?',
    a: ['ASBR', 'ABR', 'BDR', 'Gerinchálózati router'],
    m: 'ASBR = Autonomous System Boundary Router: legalább egy interfésze másik autonóm rendszerre néz.' },
  { t: 'ospf-tobb', q: 'Hányas típusú LSA-t küld minden router a közvetlen linkjeiről?', be: ['1', '1-es'],
    m: 'Az 1-es típusú (router) LSA csak a saját területét árasztja el.' },
  { t: 'ospf-tobb', q: 'Ki állítja elő a 2-es típusú (network) LSA-t?',
    a: ['A DR', 'Az ABR', 'Az ASBR', 'Minden router'],
    m: 'A DR hirdeti vele a többszörös hozzáférésű hálózat routereit. Nem jut ki a területről.' },
  { t: 'ospf-tobb', q: 'Hányas típusú LSA-val hirdeti az ABR egy másik terület hálózatait?', be: ['3', '3-as'],
    m: 'A 3-as típusú (summary) LSA. Az irányítótáblában O IA útvonal lesz belőle.' },
  { t: 'ospf-tobb', q: 'Mire való a 4-es típusú LSA?',
    a: ['Megmondja, hol van az ASBR és hogyan érhető el', 'Külső hálózatokat hirdet', 'A DR-t azonosítja', 'A router közvetlen linkjeit írja le'],
    m: 'A 4-es LSA-t az ABR állítja elő, de csak akkor, ha van ASBR a területen.' },
  { t: 'ospf-tobb', q: 'Hányas típusú LSA hirdeti a külső hálózatokat az egész autonóm rendszerben?', be: ['5', '5-ös'],
    m: 'Az 5-ös típusú (external) LSA-t az ASBR küldi, és az egész AS-t elárasztja.' },
  { t: 'ospf-tobb', q: 'Mit jelent az irányítótáblában az O IA jelzés?',
    a: ['Területek közötti (interarea) útvonal', 'Területen belüli útvonal', 'Külső útvonal', 'Alapértelmezett útvonal'],
    m: 'O = területen belüli, O IA = területek közötti (3-as LSA), O E1/E2 = külső (5-ös LSA).' },
  { t: 'ospf-tobb', q: 'Milyen jelzéssel szerepel az irányítótáblában egy külső, OSPF-be behozott útvonal?',
    a: ['O E1 vagy O E2', 'O IA', 'O', 'C'],
    m: 'A külső útvonalak 1-es (E1) vagy 2-es (E2) típusú külső útvonalként jelennek meg.' },
  { t: 'ospf-tobb', q: 'Min kell áthaladnia a két normál terület közötti forgalomnak?',
    a: ['A gerinchálózati területen (area 0)', 'Egy ASBR-en', 'A legkisebb számú területen', 'Közvetlenül mehet a két terület között'],
    m: 'Minden területek közötti (interarea) forgalom érinti a 0-s területet.' },
  { t: 'ospf-tobb', q: 'Legfeljebb hány router legyen egy területen a Cisco ajánlása szerint?', be: ['50'],
    m: 'Ajánlás: területenként max. 50 router, routerenként max. 3 terület és max. 60 szomszéd.' },
  { t: 'ospf-tobb', q: 'Legfeljebb hány területhez tartozzon egy router a Cisco ajánlása szerint?', be: ['3', 'három'],
    m: 'Ajánlás: területenként max. 50 router, routerenként max. 3 terület és max. 60 szomszéd.' },
  { t: 'ospf-tobb', q: 'Hol állítható be útvonal-összevonás OSPF-ben?',
    a: ['Csak ABR-en és ASBR-en', 'Bármelyik routeren', 'Csak a DR-en', 'Csak belső routeren'],
    m: 'Az OSPF nem von össze automatikusan; kézzel kell, és csak a határroutereken lehet.' },
  { t: 'ospf-tobb', q: 'Melyik paranccsal von össze útvonalakat az ABR?',
    a: ['area 1 range 10.1.0.0 255.255.252.0', 'summary-address 10.1.0.0 255.255.252.0', 'ip summary 10.1.0.0/22', 'network 10.1.0.0 0.0.3.255 summary'],
    m: 'area terület range cím maszk – router konfigurációs módban, alhálózati maszkkal.' },
  { t: 'ospf-tobb', q: 'Mennyi lesz az összevont útvonal metrikája?',
    a: ['A tartományba eső alhálózatok legkisebb költsége', 'A legnagyobb költség', 'A költségek összege', 'Mindig 1'],
    m: 'Az összevont útvonal a tartomány alhálózatai közül a legalacsonyabb költséget kapja.' },
  { t: 'ospf-tobb', q: 'Mit tesz a router, amikor 3-as típusú LSA érkezik a területére?',
    a: ['Beírja vagy törli az útvonalat, de nem futtat teljes SPF-et', 'Mindig újrafuttatja a teljes SPF-et', 'Eldobja az LSA-t', 'Új DR választást indít'],
    m: 'Ez a több terület egyik előnye: a változás hatása nem terjed át SPF-számításként.' },
  { t: 'ospf-tobb', q: 'Melyik paranccsal nézhető meg az LSDB tartalma LSA-típusonként?',
    be: ['show ip ospf database'], ios: true,
    m: 'show ip ospf database – Router, Net, Summary Net link state-ek területenként.' },
  { t: 'ospf-tobb', q: 'Melyik NEM normál területtípus?',
    a: ['Tranzit terület', 'Elzárt (stub)', 'Teljesen elzárt (totally stubby)', 'Részben elzárt (NSSA)'],
    m: 'A tranzit terület maga a gerinc (area 0). Normál altípusok: szabványos, stub, totally stubby, NSSA.' },
  { t: 'ospf-tobb', q: 'Mi a kapcsolatállapot-azonosítója egy 1-es típusú LSA-nak?',
    a: ['A küldő router ID-je', 'A DR interfészének IP-címe', 'A hálózat címe', 'Az ASBR router ID-je'],
    m: '1-es: a küldő router ID-je; 2-es: a DR interfészcíme; 3-as: a hálózat címe; 4-es: az ASBR router ID-je; 5-ös: a külső hálózat címe.' },

  /* =====================================================================
   * PORTOK, CÍMEK, ALAPOK
   * ===================================================================== */
  { t: 'halo-alap', q: 'Melyik porton figyel az SSH?', be: ['22'], m: 'SSH = TCP 22. A Telnet a 23-as.' },
  { t: 'halo-alap', q: 'Melyik porton figyel a Telnet?', be: ['23'], m: 'Telnet = TCP 23, titkosítatlan – helyette SSH (22).' },
  { t: 'halo-alap', q: 'Melyik portot használja a DNS?', be: ['53'], m: 'DNS = 53 (UDP, nagy válaszoknál és zónaátvitelnél TCP).' },
  { t: 'halo-alap', q: 'Melyik porton megy a HTTPS?', be: ['443'], m: 'HTTP = 80, HTTPS = 443.' },
  { t: 'halo-alap', q: 'Melyik portot használja a TFTP?', be: ['69'], m: 'TFTP = UDP 69. Az FTP TCP 20 és 21.' },
  { t: 'halo-alap', q: 'Melyik porton küld levelet az SMTP?', be: ['25'], m: 'SMTP = 25 (küldés), POP3 = 110, IMAP = 143 (letöltés).' },
  { t: 'halo-alap', q: 'Melyik porton tölti le a leveleket a POP3?', be: ['110'], m: 'POP3 = 110, IMAP = 143, SMTP = 25.' },
  { t: 'halo-alap', q: 'Melyik két UDP portot használja a DHCP?',
    a: ['67 (szerver) és 68 (kliens)', '53 és 54', '20 és 21', '161 és 162'],
    m: 'DHCP: a szerver a 67-es, a kliens a 68-as UDP porton.' },
  { t: 'halo-alap', q: 'Mennyi a statikus útvonal adminisztratív távolsága?', be: ['1'],
    m: 'Közvetlenül csatlakozó 0, statikus 1, EIGRP 90, OSPF 110, RIP 120.' },
  { t: 'halo-alap', q: 'Mennyi a RIP adminisztratív távolsága?', be: ['120'],
    m: 'Közvetlenül csatlakozó 0, statikus 1, EIGRP 90, OSPF 110, RIP 120.' },
  { t: 'halo-alap', q: 'Melyik a privát címtartomány?',
    a: ['172.16.0.0 – 172.31.255.255', '172.0.0.0 – 172.255.255.255', '192.169.0.0 – 192.169.255.255', '11.0.0.0 – 11.255.255.255'],
    m: 'Privát: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16.' },
  { t: 'halo-alap', q: 'Mit jelent, ha egy gép 169.254.x.x címet kapott?',
    a: ['Nem kapott választ a DHCP-szervertől (APIPA)', 'Publikus címet kapott', 'Loopback címe van', 'IPv6-ra váltott'],
    m: 'A 169.254.0.0/16 az APIPA tartomány: a gép magának osztott címet, mert nem jött DHCP-válasz.' },
  { t: 'halo-alap', q: 'Hány használható gépcím van egy /27-es hálózatban?', be: ['30'],
    m: '32 − 27 = 5 bit → 2⁵ = 32 cím, mínusz hálózati és broadcast = 30.' },
  { t: 'halo-alap', q: 'Mi az alhálózati maszk a /28-hoz?', be: ['255.255.255.240'],
    m: '/28: az utolsó oktettben 4 bit hálózat → 128+64+32+16 = 240.' },
  { t: 'halo-alap', q: 'Melyik rétegben dolgozik a router az OSI modellben?',
    a: ['3. – hálózati réteg', '2. – adatkapcsolati réteg', '4. – szállítási réteg', '1. – fizikai réteg'],
    m: 'Router: 3. réteg (IP-cím alapján). Switch: 2. réteg (MAC-cím alapján).' },
  { t: 'halo-alap', q: 'Melyik parancs menti a futó konfigurációt, hogy újraindítás után is megmaradjon?',
    be: ['copy running-config startup-config', 'write memory', 'write'], ios: true,
    m: 'copy running-config startup-config (röviden: copy run start vagy wr).' },

  /* =====================================================================
   * LINUX: TÖRTÉNET
   * ===================================================================== */
  { t: 'linux-tortenet', q: 'Mit jelent szigorúan véve a „Linux” szó?',
    a: ['Csak a rendszermagot (kernelt)', 'A teljes operációs rendszert', 'Egy disztribúciót', 'A GNU programok gyűjteményét'],
    m: 'A Linux a kernel; a teljes rendszer pontos neve GNU/Linux.' },
  { t: 'linux-tortenet', q: 'Ki kezdte el fejleszteni a Linux kernelt?',
    a: ['Linus Torvalds', 'Richard Stallman', 'Andrew Tanenbaum', 'Dennis Ritchie'],
    m: 'Linus Torvalds, svéd anyanyelvű finn egyetemista, 1991-ben.' },
  { t: 'linux-tortenet', q: 'Melyik évben kezdődött a Linux kernel fejlesztése?', be: ['1991'],
    m: '1991. A GNU projekt 1983-ban, a Minix 1987-ben indult.' },
  { t: 'linux-tortenet', q: 'Ki indította a GNU projektet?',
    a: ['Richard M. Stallman', 'Linus Torvalds', 'Andrew S. Tanenbaum', 'Bill Gates'],
    m: 'Richard Matthew Stallman (RMS), 1983-ban.' },
  { t: 'linux-tortenet', q: 'Melyik évben indult a GNU projekt?', be: ['1983'],
    m: '1983 – szabad szoftveres mozgalom, célja szabadon felhasználható, minőségi szoftverek készítése.' },
  { t: 'linux-tortenet', q: 'Mi a GNU projekt saját, máig el nem készült kernele?',
    a: ['GNU/Hurd', 'Minix', 'ELKS', 'XNU'],
    m: 'A Hurd fejlesztése elhúzódott, ezért lett a GNU programok alá a Linux kernel.' },
  { t: 'linux-tortenet', q: 'Ki írta a Minixet?',
    a: ['Andrew S. Tanenbaum', 'Linus Torvalds', 'Richard Stallman', 'Ken Thompson'],
    m: 'Tanenbaum, Hollandiában élő amerikai professzor, 1987-ben, oktatási céllal.' },
  { t: 'linux-tortenet', q: 'Miért volt különleges a Minix?',
    a: ['Bárki elolvashatta a forráskódját', 'Ez volt a leggyorsabb rendszer', 'Ingyen adták minden PC-hez', 'Grafikus felülete volt'],
    m: 'Kb. 12 000 sornyi forráskódja a könyvvel együtt hozzáférhető volt – először olvashatta bárki egy operációs rendszer forrását.' },
  { t: 'linux-tortenet', q: 'Mi a rendszer pontos neve, ha a kernelt és az alapprogramokat is beleértjük?', be: ['GNU/Linux', 'GNU Linux'],
    m: 'GNU/Linux – a Debian így használja, a SuSE nem.' },
  { t: 'linux-tortenet', q: 'Milyen licenc alatt jelenik meg a Linux kernel?',
    a: ['GPL (v2)', 'LGPL', 'MIT', 'BSD'],
    m: 'GNU General Public License, 2-es verzió. A kernel nem váltott v3-ra.' },
  { t: 'linux-tortenet', q: 'Mire kötelez a GPL, ha valaki Linux disztribúciót terjeszt?',
    a: ['Elérhetővé kell tennie a forráskódot és a módosításait', 'Jogdíjat kell fizetnie Torvaldsnak', 'Nem kérhet érte pénzt', 'Regisztrálnia kell a Linux Foundationnél'],
    m: 'A forrásnak megtekinthetőnek, módosíthatónak és ugyanilyen feltételekkel továbbadhatónak kell maradnia.' },
  { t: 'linux-tortenet', q: 'Milyen licencű az X Window System?',
    a: ['MIT', 'GPL', 'LGPL', 'Zárt'],
    m: 'X Window System: MIT licenc. Sok programkönyvtár LGPL (engedékenyebb a GPL-nél).' },
  { t: 'linux-tortenet', q: 'Melyik cég perelte be az IBM-et arra hivatkozva, hogy UNIX-kód került a Linuxba?',
    a: ['SCO', 'Novell', 'Microsoft', 'Red Hat'],
    m: 'Az SCO. A Novell megtámadta az SCO-t a UNIX jogai miatt, és az SCO veszített.' },
  { t: 'linux-tortenet', q: 'Melyik szervezet kezeli a „Linux” védjegy ügyeit?',
    a: ['Linux Mark Institute (LMI)', 'Free Software Foundation', 'OSRM', 'GNU projekt'],
    m: 'A védjegy Torvalds nevén van, az ügyeket az LMI intézi – miután 1997-ben megnyerték a pert Della Croce ellen.' },
  { t: 'linux-tortenet', q: 'Miért nem terjedt el otthon a UNIX a 80-as években?',
    a: ['Drága volt, nagygépekre tervezték, és zárt volt a forrása', 'Nem tudott hálózatot kezelni', 'Csak Apple gépeken futott', 'Nem volt többfelhasználós'],
    m: 'Főleg intézmények, kutatóközpontok és iskolák használták.' },

  /* =====================================================================
   * LINUX: JELLEMZŐK
   * ===================================================================== */
  { t: 'linux-jellemzok', q: 'Melyik NEM alaptulajdonsága a GNU/Linuxnak?',
    a: ['Egyfelhasználós', 'Többfeladatos', 'Multiplatformos', 'Nyílt forrású'],
    m: 'Nyílt forrású, többfeladatos, többfelhasználós, multiplatformos, hálózati operációs rendszer.' },
  { t: 'linux-jellemzok', q: 'Kik fejlesztik a Linux kernelt túlnyomó többségben?',
    a: ['Cégek fizetett fejlesztői, munkaidőben', 'Egyetemisták szabadidejükben', 'Kizárólag Linus Torvalds', 'Állami kutatóintézetek'],
    m: 'A felmérések szerint az otthoni, hobbi fejlesztők aránya csak kb. 7–11%.' },
  { t: 'linux-jellemzok', q: 'Melyik cég járt az élen a kernelfejlesztésben a tanult felmérés szerint?',
    a: ['Red Hat', 'Microsoft', 'Apple', 'Canonical'],
    m: 'Sorrend: Red Hat, IBM, Novell, Linux Foundation, Intel, Oracle, Google.' },
  { t: 'linux-jellemzok', q: 'Kooperatív multitaszknál ki dönt arról, mikor vált a processzor másik feladatra?',
    a: ['Maga a futó feladat, önként lemondva', 'Az ütemező, az időszelet lejártakor', 'A felhasználó', 'A hardver megszakítása'],
    m: 'A feladat önként adja át a vezérlést (yielding) – ezért egy hibás program mindent megakaszt.' },
  { t: 'linux-jellemzok', q: 'Mi a kooperatív multitaszk fő hátránya?',
    a: ['Egy végtelen ciklusba került feladat lefoglalja az egész magot', 'Túl sok memóriát használ', 'Nem működik egy magon', 'Lassú a feladatváltás'],
    m: 'Ha a feladat nem jut el addig a pontig, ahol átadná a vezérlést, senki más nem fut.' },
  { t: 'linux-jellemzok', q: 'Hogy hívják azt az időtartamot, amennyit egy folyamat egyhuzamban futhat preemptív ütemezésnél?', be: ['timeslice', 'időszelet', 'time slice'],
    m: 'Timeslice (időszelet). A lejártakor az ütemező elveszi a processzort – ez a preemptálás.' },
  { t: 'linux-jellemzok', q: 'Melyik rendszer használt kooperatív multitaszkot?',
    a: ['Mac OS 9', 'Linux', 'Windows 10', 'modern UNIX-ok'],
    m: 'A modern rendszerek mind preemptívek; a Mac OS 9 és elődei viszonylag késői kivételek.' },
  { t: 'linux-jellemzok', q: 'Melyik Intel processzortól kezdve futtatható Linux PC-n?',
    a: ['386', '286', '8086', 'Pentium'],
    m: 'A 386-os az első, amelyik képes a preemptív működéshez szükséges védett módra.' },
  { t: 'linux-jellemzok', q: 'Melyik folyamattípust sorolja előre a Linux ütemezője?',
    a: ['Az I/O-függőt', 'A processzorfüggőt', 'A legrégebben futót', 'A legtöbb memóriát használót'],
    m: 'Az I/O-függő folyamat gyakran, de rövid ideig fut – ettől lesz jó a rendszer válaszideje.' },
  { t: 'linux-jellemzok', q: 'Mi az ütemezési irányelv (scheduler policy) két ellentétes célja?',
    a: ['Gyors válaszidő és nagy áteresztőképesség', 'Kevés memória és kevés lemezhasználat', 'Biztonság és sebesség', 'Sok felhasználó és kevés folyamat'],
    m: 'Low latency kontra throughput – a kettő között kell egyensúlyozni.' },
  { t: 'linux-jellemzok', q: 'Mi a nice érték tartománya?',
    a: ['−20 … +19', '0 … 99', '1 … 10', '−10 … +10'],
    m: 'nice: −20 … +19, alapérték 0. A valós idejű prioritás tartománya 0 … 99.' },
  { t: 'linux-jellemzok', q: 'Mi a nice érték alapértelmezése?', be: ['0'],
    m: 'Alapérték 0. Nagyobb érték = alacsonyabb prioritás.' },
  { t: 'linux-jellemzok', q: 'Melyik folyamat kap hamarabb processzort?',
    a: ['Amelyiknek −10 a nice értéke', 'Amelyiknek 0 a nice értéke', 'Amelyiknek +10 a nice értéke', 'Amelyiknek +19 a nice értéke'],
    m: 'A kisebb nice érték magasabb prioritás. A +19 a legudvariasabb („nice”) folyamat.' },
  { t: 'linux-jellemzok', q: 'Mi a valós idejű prioritás tartománya Linuxon?',
    a: ['0 … 99', '−20 … +19', '1 … 255', '0 … 7'],
    m: '0 … 99, a POSIX szabvány szerint. A valós idejű feladatok megelőzik a normál folyamatokat.' },
  { t: 'linux-jellemzok', q: 'Milyen elv szerint futnak az azonos prioritású folyamatok?', be: ['round-robin', 'round robin'],
    m: 'Round-robin: körbe forogva, mindenki sorra kerül.' },
  { t: 'linux-jellemzok', q: 'Ki írta át jelentősen a Linux ütemezőjét a 2.5 → 2.6 váltáskor?',
    a: ['Molnár Ingo', 'Linus Torvalds', 'Alan Cox', 'Greg Kroah-Hartman'],
    m: 'Molnár Ingo magyar kernelfejlesztő, 2003 körül.' },

  /* =====================================================================
   * LINUX: FELÉPÍTÉS
   * ===================================================================== */
  { t: 'linux-felepites', q: 'Mire készült eredetileg a Linux?',
    a: ['A 386-os processzor védett módjának tanulmányozására', 'Webszerverek futtatására', 'Mobiltelefonokra', 'Szuperszámítógépekre'],
    m: 'Tanulóprojektnek indult; a közösség később főleg kiszolgálókra szánta.' },
  { t: 'linux-felepites', q: 'Milyen típusú a Linux kernel?',
    a: ['Moduláris monolitikus', 'Mikrokernel', 'Hibrid', 'Exokernel'],
    m: 'Moduláris monolitikus: egységes, de a modulok menet közben betölthetők és eltávolíthatók.' },
  { t: 'linux-felepites', q: 'Melyik rendszer mikrokerneles?',
    a: ['Minix', 'Linux', 'Windows NT', 'klasszikus UNIX'],
    m: 'Minix: mikrokernel. Windows NT: hibrid. Klasszikus UNIX: monolitikus. Linux: moduláris monolitikus.' },
  { t: 'linux-felepites', q: 'Milyen kernele van a Windows NT-nek?',
    a: ['Hibrid', 'Monolitikus', 'Mikrokernel', 'Moduláris monolitikus'],
    m: 'A Windows NT hibrid kernelű.' },
  { t: 'linux-felepites', q: 'Mit jelent a LAMP betűszó?',
    a: ['Linux, Apache, MySQL, Perl/PHP/Python', 'Linux, Apple, Microsoft, Python', 'LAN, Apache, Mail, Proxy', 'Linux, Admin, Memory, Process'],
    m: 'A LAMP a webes rendszerek klasszikus alapja.' },
  { t: 'linux-felepites', q: 'Miért népszerű a Linux szerveren?',
    a: ['Stabil, hosszú az üzemideje, és nem kell hozzá grafikus felület', 'Mert minden windowsos program fut rajta', 'Mert csak fizetős támogatással adják', 'Mert nem kell hozzá hálózat'],
    m: 'A három ok: stabilitás, hosszú menetidő, grafikus felület nélkül is teljes értékű.' },
  { t: 'linux-felepites', q: 'Melyik a három legelterjedtebb asztali környezet a tananyag szerint?',
    a: ['GNOME, KDE, Cinnamon', 'Aero, Metro, Fluent', 'Xfce, LXDE, i3', 'Bash, Zsh, Fish'],
    m: 'GNOME, KDE és Cinnamon – a legérettebbek, széles nyelvi támogatással.' },
  { t: 'linux-felepites', q: 'Melyik programmal futtatható ingyen windowsos alkalmazás Linuxon?', be: ['wine'],
    m: 'Wine (ingyenes), illetve CrossOver (üzleti).' },
  { t: 'linux-felepites', q: 'Hogyan érik el a rendszerprogramok a kernel szolgáltatásait?',
    a: ['Rendszerhívásokon keresztül', 'Közvetlen hardvereléréssel', 'A grafikus felületen át', 'A BIOS-on keresztül'],
    m: 'A kernel megakadályozza a közvetlen hardverhozzáférést; a programok rendszerhívásokat használnak.' },
  { t: 'linux-felepites', q: 'Melyik két kernelrész nélkül „semmi sem megy”?',
    a: ['Folyamatkezelés és memóriakezelés', 'Hálózatkezelés és driverek', 'Fájlrendszer és grafika', 'Hang és nyomtatás'],
    m: 'A folyamatkezelés valósítja meg a többfeladatos működést, a memóriakezelés osztja szét a memóriát és a swapet.' },
  { t: 'linux-felepites', q: 'Milyen egységes felületen keresztül érik el a programok a hálózati funkciókat?',
    a: ['BSD socket', 'Virtual File System', 'POSIX thread', 'X Window'],
    m: 'Hálózat: BSD socket. Fájlrendszerek: Virtual File System (VFS).' },
  { t: 'linux-felepites', q: 'Mi a neve annak a rétegnek, amely egységessé teszi a különböző fájlrendszerek kezelését?', be: ['VFS', 'Virtual File System', 'Virtual filesystem'],
    m: 'Virtual File System – a programoknak mindegy, milyen fájlrendszer van alatta.' },
  { t: 'linux-felepites', q: 'Mi az előnye a kernelmoduloknak?',
    a: ['Csak az a driver foglal memóriát, amelyikre tényleg szükség van', 'Gyorsabb tőlük a processzor', 'Nem kell hozzájuk kernel', 'Felhasználói módban futnak'],
    m: 'A modulok működés közben betölthetők és kiiktathatók.' },
  { t: 'linux-felepites', q: 'Melyik kernel fut 386-osnál régebbi, 16 bites Intel gépeken?', be: ['ELKS'],
    m: 'Az ELKS a Linuxból származtatott kernel 8086-ra és 80286-ra.' },
  { t: 'linux-felepites', q: 'Mitől biztonságos a programtelepítés a disztribúció csomagtárolójából?',
    a: ['A csomagok ellenőrzöttek és digitálisan aláírtak', 'Mert minden program zárt forrású', 'Mert vírusirtó fut a háttérben', 'Mert csak rendszergazda internetezhet'],
    m: 'A tárolóban lévő csomagok teszteltek, az adott disztróra optimalizáltak és aláírtak.' },
  { t: 'linux-felepites', q: 'Melyik film óta használ a filmipar Linuxot a tananyag szerint?',
    a: ['Titanic (1997)', 'Toy Story (1995)', 'Avatar (2009)', 'Mátrix (1999)'],
    m: 'A Titanic óta; 2009-re a nagy stúdiók kb. 95%-a átállt.' }
];

/* =========================================================================
 * PARANCSFELADATOK – terminál
 * ========================================================================= */
const PARANCSFELADATOK = [
  { t: 'ios', q: 'Lépj privilegizált módba, majd globális konfigurációs módba.',
    lepesek: [{ p: 'Router>', c: 'enable' }, { p: 'Router#', c: 'configure terminal' }] },
  { t: 'ios', q: 'Nevezd el a routert R1-nek.',
    lepesek: [{ p: 'Router(config)#', c: 'hostname {R1}' }] },
  { t: 'ios', q: 'Állíts be titkosított privilegizált jelszót: class',
    lepesek: [{ p: 'R1(config)#', c: 'enable secret {class}' }] },
  { t: 'ios', q: 'Titkosítsd az összes, a konfigurációban olvasható jelszót.',
    lepesek: [{ p: 'R1(config)#', c: 'service password-encryption' }] },
  { t: 'ios', q: 'Kapcsold ki a hibásan beírt parancsok DNS-feloldását.',
    lepesek: [{ p: 'R1(config)#', c: 'no ip domain-lookup' }] },
  { t: 'ios', q: 'Állíts be cisco jelszót a konzolvonalra, és kérjen is jelszót belépéskor.',
    lepesek: [{ p: 'R1(config)#', c: 'line console 0' }, { p: 'R1(config-line)#', c: 'password {cisco}' }, { p: 'R1(config-line)#', c: 'login' }] },
  { t: 'ios', q: 'Add a GigabitEthernet 0/0 interfésznek a 192.168.1.1/24 címet, és kapcsold be.',
    lepesek: [{ p: 'R1(config)#', c: 'interface gigabitEthernet 0/0' }, { p: 'R1(config-if)#', c: 'ip address 192.168.1.1 255.255.255.0' }, { p: 'R1(config-if)#', c: 'no shutdown' }] },
  { t: 'ios', q: 'A Serial 0/0/0 interfész a DCE oldal: adj neki 10.0.0.1/30 címet és 64000-es órajelet.',
    lepesek: [{ p: 'R1(config)#', c: 'interface serial 0/0/0' }, { p: 'R1(config-if)#', c: 'ip address 10.0.0.1 255.255.255.252' }, { p: 'R1(config-if)#', c: 'clock rate 64000' }] },
  { t: 'ios', q: 'Mentsd el a futó konfigurációt.',
    lepesek: [{ p: 'R1#', c: ['copy running-config startup-config', 'write memory', 'write'] }] },
  { t: 'ios', q: 'Nézd meg röviden az interfészek IP-címét és állapotát.',
    lepesek: [{ p: 'R1#', c: 'show ip interface brief' }] },
  { t: 'ios', q: 'Hozd létre a 10-es VLAN-t TANAROK néven.',
    lepesek: [{ p: 'S1(config)#', c: 'vlan 10' }, { p: 'S1(config-vlan)#', c: 'name {TANAROK}' }] },
  { t: 'ios', q: 'Tedd a FastEthernet 0/5 portot hozzáférési módba, a 10-es VLAN-ba.',
    lepesek: [{ p: 'S1(config)#', c: 'interface fastEthernet 0/5' }, { p: 'S1(config-if)#', c: 'switchport mode access' }, { p: 'S1(config-if)#', c: 'switchport access vlan 10' }] },
  { t: 'ios', q: 'Állítsd trönk módba a GigabitEthernet 0/1 portot.',
    lepesek: [{ p: 'S1(config)#', c: 'interface gigabitEthernet 0/1' }, { p: 'S1(config-if)#', c: 'switchport mode trunk' }] },
  { t: 'ios', q: 'Router-on-a-stick: hozd létre a G0/0.10 alinterfészt a 10-es VLAN-hoz, 192.168.10.1/24 címmel.',
    lepesek: [{ p: 'R1(config)#', c: 'interface gigabitEthernet 0/0.10' }, { p: 'R1(config-subif)#', c: 'encapsulation dot1Q 10' }, { p: 'R1(config-subif)#', c: 'ip address 192.168.10.1 255.255.255.0' }] },
  { t: 'ios', q: 'Adj a switchnek felügyeleti címet: VLAN 1 interfész, 192.168.1.2/24, bekapcsolva.',
    lepesek: [{ p: 'S1(config)#', c: 'interface vlan 1' }, { p: 'S1(config-if)#', c: 'ip address 192.168.1.2 255.255.255.0' }, { p: 'S1(config-if)#', c: 'no shutdown' }] },
  { t: 'ios', q: 'Vegyél fel alapértelmezett statikus útvonalat a 10.0.0.2 következő ugrás felé.',
    lepesek: [{ p: 'R1(config)#', c: 'ip route 0.0.0.0 0.0.0.0 10.0.0.2' }] },
  { t: 'ios', q: 'Vegyél fel statikus útvonalat a 192.168.2.0/24 hálózathoz a 10.0.0.2 címen keresztül.',
    lepesek: [{ p: 'R1(config)#', c: 'ip route 192.168.2.0 255.255.255.0 10.0.0.2' }] },
  { t: 'ios', q: 'DHCP: zárd ki a kiosztásból a 192.168.1.1 – 192.168.1.10 címeket.',
    lepesek: [{ p: 'R1(config)#', c: 'ip dhcp excluded-address 192.168.1.1 192.168.1.10' }] },
  { t: 'ios', q: 'Hozz létre LAN nevű DHCP poolt a 192.168.1.0/24 hálózatra, 192.168.1.1 átjáróval és 8.8.8.8 DNS-sel.',
    lepesek: [{ p: 'R1(config)#', c: 'ip dhcp pool {LAN}' }, { p: 'R1(dhcp-config)#', c: 'network 192.168.1.0 255.255.255.0' }, { p: 'R1(dhcp-config)#', c: 'default-router 192.168.1.1' }, { p: 'R1(dhcp-config)#', c: 'dns-server 8.8.8.8' }] },
  { t: 'ios', q: 'SSH előkészítése: állítsd be a suli.local tartománynevet, és generálj 1024 bites RSA kulcsot.',
    lepesek: [{ p: 'R1(config)#', c: 'ip domain-name {suli.local}' }, { p: 'R1(config)#', c: ['crypto key generate rsa general-keys modulus 1024', 'crypto key generate rsa modulus 1024'] }] },
  { t: 'ios', q: 'A VTY 0–4 vonalakon csak SSH legyen engedélyezve, helyi felhasználókkal.',
    lepesek: [{ p: 'R1(config)#', c: 'line vty 0 4' }, { p: 'R1(config-line)#', c: 'transport input ssh' }, { p: 'R1(config-line)#', c: 'login local' }] },
  { t: 'ios', q: 'Hozz létre admin nevű helyi felhasználót titkos123 titkosított jelszóval.',
    lepesek: [{ p: 'R1(config)#', c: 'username {admin} secret {titkos123}' }] },
  { t: 'ios', q: 'PAT: fordítsd az 1-es ACL címeit a GigabitEthernet 0/1 interfész címére.',
    lepesek: [{ p: 'R1(config)#', c: 'ip nat inside source list 1 interface gigabitEthernet 0/1 overload' }] },
  { t: 'ios', q: 'Engedélyezd az 1-es szabványos ACL-ben a 192.168.1.0/24 hálózatot.',
    lepesek: [{ p: 'R1(config)#', c: 'access-list 1 permit 192.168.1.0 0.0.0.255' }] },

  { t: 'ospf-egy', q: 'Indítsd el a 10-es OSPF folyamatot, és adj neki 1.1.1.1 router ID-t.',
    lepesek: [{ p: 'R1(config)#', c: 'router ospf 10' }, { p: 'R1(config-router)#', c: 'router-id 1.1.1.1' }] },
  { t: 'ospf-egy', q: 'Hirdesd a 192.168.1.0/24 hálózatot a 0-s területben.',
    lepesek: [{ p: 'R1(config-router)#', c: 'network 192.168.1.0 0.0.0.255 area 0' }] },
  { t: 'ospf-egy', q: 'Hirdesd a 10.0.0.0/30 pont-pont linket a 0-s területben.',
    lepesek: [{ p: 'R1(config-router)#', c: 'network 10.0.0.0 0.0.0.3 area 0' }] },
  { t: 'ospf-egy', q: 'A LAN felé néző GigabitEthernet 0/0 ne küldjön OSPF Hello csomagot.',
    lepesek: [{ p: 'R1(config-router)#', c: 'passive-interface gigabitEthernet 0/0' }] },
  { t: 'ospf-egy', q: 'Állítsd a referencia-sávszélességet 1000 Mbps-ra.',
    lepesek: [{ p: 'R1(config-router)#', c: 'auto-cost reference-bandwidth 1000' }] },
  { t: 'ospf-egy', q: 'Hirdesd tovább az alapértelmezett útvonalat az OSPF szomszédoknak.',
    lepesek: [{ p: 'R1(config-router)#', c: 'default-information originate' }] },
  { t: 'ospf-egy', q: 'Tedd a GigabitEthernet 0/0 interfészt közvetlenül (network parancs nélkül) a 10-es OSPF folyamat 0-s területébe.',
    lepesek: [{ p: 'R1(config)#', c: 'interface gigabitEthernet 0/0' }, { p: 'R1(config-if)#', c: 'ip ospf 10 area 0' }] },
  { t: 'ospf-egy', q: 'Érd el, hogy ez a router legyen a DR: állítsd az interfész OSPF prioritását 255-re.',
    lepesek: [{ p: 'R1(config-if)#', c: 'ip ospf priority 255' }] },
  { t: 'ospf-egy', q: 'Állítsd az interfészen a Hello időközt 5, a Dead időközt 20 másodpercre.',
    lepesek: [{ p: 'R1(config-if)#', c: 'ip ospf hello-interval 5' }, { p: 'R1(config-if)#', c: 'ip ospf dead-interval 20' }] },
  { t: 'ospf-egy', q: 'Listázd az OSPF szomszédokat.',
    lepesek: [{ p: 'R1#', c: 'show ip ospf neighbor' }] },
  { t: 'ospf-egy', q: 'Indítsd újra az OSPF folyamatot, hogy az új router ID érvénybe lépjen.',
    lepesek: [{ p: 'R1#', c: 'clear ip ospf process' }] },

  { t: 'ospf-tobb', q: 'R1 ABR: hirdesd a 10.1.1.0/24 hálózatot az 1-es, a 192.168.10.0/30 linket a 0-s területben.',
    lepesek: [{ p: 'R1(config)#', c: 'router ospf 10' }, { p: 'R1(config-router)#', c: 'network 10.1.1.0 0.0.0.255 area 1' }, { p: 'R1(config-router)#', c: 'network 192.168.10.0 0.0.0.3 area 0' }] },
  { t: 'ospf-tobb', q: 'Vond össze az 1-es terület hálózatait egyetlen 10.1.0.0/22 útvonallá.',
    lepesek: [{ p: 'R1(config-router)#', c: 'area 1 range 10.1.0.0 255.255.252.0' }] },
  { t: 'ospf-tobb', q: 'Nézd meg csak az OSPF-ből tanult útvonalakat (O, O IA, O E2).',
    lepesek: [{ p: 'R1#', c: 'show ip route ospf' }] },
  { t: 'ospf-tobb', q: 'Nézd meg a kapcsolatállapot-adatbázis (LSDB) tartalmát.',
    lepesek: [{ p: 'R1#', c: 'show ip ospf database' }] },
  { t: 'ospf-tobb', q: 'Listázd röviden, melyik interfész melyik OSPF területben van.',
    lepesek: [{ p: 'R1#', c: 'show ip ospf interface brief' }] }
];

/** A terminálfeladatok témái (a kvíz témái mellé) */
const PARANCSTEMAK = [
  { id: 'ios',       nev: 'IOS alapok, switching, szolgáltatások' },
  { id: 'ospf-egy',  nev: 'Egyterületű OSPF' },
  { id: 'ospf-tobb', nev: 'Többterületű OSPF' }
];

/* =========================================================================
 * KARTYAK – tanulókártyák
 * ========================================================================= */
const PAKLIK = [
  { id: 'portok',  nev: 'Portszámok' },
  { id: 'ad',      nev: 'Adminisztratív távolságok' },
  { id: 'ospf',    nev: 'OSPF fogalmak' },
  { id: 'linux',   nev: 'Linux fogalmak' }
  /* + a parancstár kategóriái paklinként, automatikusan */
];

const KARTYAK = [
  { t: 'portok', e: 'FTP', h: 'TCP 20 (adat) és 21 (vezérlés)' },
  { t: 'portok', e: 'SSH', h: 'TCP 22' },
  { t: 'portok', e: 'Telnet', h: 'TCP 23' },
  { t: 'portok', e: 'SMTP', h: 'TCP 25' },
  { t: 'portok', e: 'DNS', h: '53 (UDP és TCP)' },
  { t: 'portok', e: 'DHCP', h: 'UDP 67 (szerver) és 68 (kliens)' },
  { t: 'portok', e: 'TFTP', h: 'UDP 69' },
  { t: 'portok', e: 'HTTP', h: 'TCP 80' },
  { t: 'portok', e: 'POP3', h: 'TCP 110' },
  { t: 'portok', e: 'NTP', h: 'UDP 123' },
  { t: 'portok', e: 'IMAP', h: 'TCP 143' },
  { t: 'portok', e: 'SNMP', h: 'UDP 161 (trap: 162)' },
  { t: 'portok', e: 'HTTPS', h: 'TCP 443' },
  { t: 'portok', e: 'Syslog', h: 'UDP 514' },
  { t: 'portok', e: 'RDP (távoli asztal)', h: 'TCP 3389' },

  { t: 'ad', e: 'Közvetlenül csatlakozó hálózat', h: '0' },
  { t: 'ad', e: 'Statikus útvonal', h: '1' },
  { t: 'ad', e: 'Külső BGP (eBGP)', h: '20' },
  { t: 'ad', e: 'EIGRP (belső)', h: '90' },
  { t: 'ad', e: 'OSPF', h: '110' },
  { t: 'ad', e: 'RIP', h: '120' },

  { t: 'ospf', e: '1-es típusú LSA', h: 'Router LSA – minden router küldi, a területen belül marad' },
  { t: 'ospf', e: '2-es típusú LSA', h: 'Network LSA – a DR küldi, a területen belül marad' },
  { t: 'ospf', e: '3-as típusú LSA', h: 'Summary LSA – az ABR hirdeti vele más területek hálózatait (O IA)' },
  { t: 'ospf', e: '4-es típusú LSA', h: 'ASBR Summary – az ABR küldi: hol van az ASBR' },
  { t: 'ospf', e: '5-ös típusú LSA', h: 'External LSA – az ASBR küldi, az egész AS-ben terjed (O E1/E2)' },
  { t: 'ospf', e: 'ABR', h: 'Területi határrouter: interfészei több területhez tartoznak' },
  { t: 'ospf', e: 'ASBR', h: 'Autonóm rendszer határroutere: külső hálózathoz is csatlakozik' },
  { t: 'ospf', e: 'OSPF Hello / Dead (Ethernet)', h: '10 mp / 40 mp' },
  { t: 'ospf', e: 'OSPF multicast címek', h: '224.0.0.5 (mindenki), 224.0.0.6 (DR és BDR)' },
  { t: 'ospf', e: 'Router ID kiválasztási sorrendje', h: 'router-id parancs → legnagyobb loopback → legnagyobb aktív interfész IP' },
  { t: 'ospf', e: 'DR választás szempontjai', h: 'Legnagyobb prioritás, utána legnagyobb router ID (0 prioritás: kizárva)' },
  { t: 'ospf', e: 'OSPF költség képlete', h: 'Referencia-sávszélesség (alap 100 Mbps) / interfész sávszélessége' },
  { t: 'ospf', e: 'Az OSPF szomszédsági állapotok sorrendje', h: 'Down → Init → Two-Way → ExStart → Exchange → Loading → Full' },
  { t: 'ospf', e: 'Az 5 OSPF csomagtípus', h: 'Hello, DBD, LSR, LSU, LSAck' },

  { t: 'linux', e: 'Linus Torvalds', h: 'A Linux kernel elindítója, 1991' },
  { t: 'linux', e: 'Richard M. Stallman', h: 'A GNU projekt alapítója, 1983' },
  { t: 'linux', e: 'Andrew S. Tanenbaum', h: 'A Minix írója, 1987 (oktatási célú, nyílt forrású mikrokernel)' },
  { t: 'linux', e: 'GPL', h: 'GNU General Public License: a forrást és a módosításokat elérhetővé kell tenni' },
  { t: 'linux', e: 'Disztribúció', h: 'Kernel + alaprendszer + válogatott, testre szabott programok összeállítása' },
  { t: 'linux', e: 'Preemptív multitaszk', h: 'Az ütemező az időszelet (timeslice) lejártakor elveszi a processzort' },
  { t: 'linux', e: 'Kooperatív multitaszk', h: 'A feladat önként adja át a processzort (yielding)' },
  { t: 'linux', e: 'nice érték', h: '−20 … +19, alap 0; a nagyobb érték alacsonyabb prioritás' },
  { t: 'linux', e: 'Valós idejű prioritás', h: '0 … 99 (POSIX)' },
  { t: 'linux', e: 'LAMP', h: 'Linux, Apache, MySQL, Perl/PHP/Python' },
  { t: 'linux', e: 'A Linux kernel típusa', h: 'Moduláris monolitikus' },
  { t: 'linux', e: 'VFS', h: 'Virtual File System: egységes felület a fájlrendszerekhez' },
  { t: 'linux', e: 'I/O-függő folyamat', h: 'Kevés számítás, sok várakozás – az ütemező előre sorolja' },
  { t: 'linux', e: 'Linux Mark Institute', h: 'A „Linux” védjegy ügyeit intéző szervezet' }
];
